[package]
name = "bridge-indexer-db"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }

[dependencies]
diesel = { workspace = true, features = ["postgres", "numeric"]}
diesel_migrations = { workspace = true }
bigdecimal = { workspace = true }

[features]
default = []
client = []
server = []

[lints]
workspace = true
